- name: Configure nginx web server to use our custom folder to pick the html pages in Ubuntu
  copy: src=default dest=/etc/nginx/sites-available/default
  notify: 
  - Restart nginx web server to apply config changes in Ubuntu
