- name: Configure nginx web server to use our custom folder to pick the html pages in CentOS 
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
  - Restart nginx web server to apply config changes in CentOS 
