---
# tasks file for nginx
- include: nginx-common-tasks.yml
- include: "install-nginx-{{ansible_distribution|lower}}.yml" 
- include: "start-nginx-{{ansible_distribution|lower}}.yml" 
- include: "configure-nginx-{{ansible_distribution|lower}}.yml" 
- include: "configure-nginx-{{ansible_distribution|lower}}.yml" 
